export default Object.freeze({
  INIT: "INIT_FROM_PARAMS",
  SET_ACTIVE_KEY: "SET_ACTIVE_KEY",
  SET_WORK_TIME: "SET_WORK_TIME",
  SET_BREAK: "SET_BREAK",
  SET_ROUNDS: "SET_ROUNDS",
  SET_TITLE: "SET_TITLE",
  SET_PREVIOUS: "SET_PREVIOUS",
  REVERT_PREVIOUS: "REVERT_PREVIOUS",
  FLAG_DIRTY: "FLAG_DIRTY",
  TOGGLE_APPLY_FLAG: "TOGGLE_APPLY_FLAG",
});
