export default Object.freeze({
  INIT: "INIT_FROM_PARAMS",
  SET_ACTIVE_KEY: "SET_ACTIVE_KEY",
  SET_PREVIOUS: "SET_PREVIOUS",
  REVERT_PREVIOUS: "REVERT_PREVIOUS",
  SET_WARMUP: "SET_WARMUP",
  SET_COOLDOWN: "SET_COOLDOWN",
  TOGGLE_APPLY: "TOGGLE_APPLY",
  TOGGLE_REFRESH: "TOGGLE_REFRESH",
});
