export default Object.freeze({
  INIT_FROM_PARAMS: "INIT_FROM_PARAMS",
  SET_EXERCISE_DATA: "INIT_EXERCISES",
  SKIP_FORWARD: "SKIP_FORWARD",
  SKIP_BACKWARD: "SKIP_BACKWARD",
  SKIP_AMOUNT: "SKIP_AMOUNT",
  ELAPSE: "ELAPSE",
  TOGGLE_IS_PLAYING: "TOGGLE_IS_PLAYING",
  RESET_TIMER: "RESET_TIMER",
  MARK_TIMER_LOAD_COMPLETE: "MARK_TIMER_LOAD_COMPLETE",
  MARK_SKIP_COMPLETE: "MARK_SKIP_COMPLETE",
  MARK_COUNTDOWN_COMPLETE: "MARK_COUNTDOWN_COMPLETE",
  CLOSE_SUCCESS_MODAL: "CLOSE_SUCCESS_MODAL",
});
