export default Object.freeze({
  INIT_FROM_PARAMS: "INIT_FROM_PARAMS",
  SET_EXERCISE_DATA: "INIT_EXERCISES",
  SKIP_FORWARD: "SKIP_FORWARD",
  SKIP_BACKWARD: "SKIP_BACKWARD",
  DECREMENT_TIMER: "DECREMENT_TIMER",
  TOGGLE_IS_PLAYING: "TOGGLE_IS_PLAYING",
  RESET_TIMER: "RESET_TIMER",
  MARK_TIMER_LOAD_COMPLETE: "MARK_TIMER_LOAD_COMPLETE",
});
