export default Object.freeze({
  INIT_FROM_PARAMS: "INIT_FROM_PARAMS",
  START_COUNTDOWN: "START_COUNTDOWN",
  SET_EXERCISE_DATA: "INIT_EXERCISES",
  SKIP_FORWARD: "SKIP_FORWARD",
  SKIP_BACKWARD: "SKIP_BACKWARD",
  TICK: "TICK",
  RESYNC_CLOCK: "RESYNC_CLOCK",
  TOGGLE_IS_PLAYING: "TOGGLE_IS_PLAYING",
  RESET_TIMER: "RESET_TIMER",
  MARK_COUNTDOWN_COMPLETE: "MARK_COUNTDOWN_COMPLETE",
  CLOSE_SUCCESS_MODAL: "CLOSE_SUCCESS_MODAL",
});
