// Some use 'argb' to specify 'alpha' or 'transparency'
export const darkTheme = {
  background: "#000000",
  backgroundFaded: "#1e1e1e",
  tileBackground: "#ffffff0c",
  secondaryBackground: "#1c1c1e",
  tertiaryBackground: "#2c2c2e",
  tertiaryTranslucentBackground: "#rgba(44, 44, 46, 0.1)",
  foreground: "#eeeeee",
  primary: "#ffffff",
  secondary: "#ebebf599",
  tertiary: "#ffffff61",
  danger: "#d93453",
  blue: "#3397f3",
  text: "#aaa",
  text87: "#ffffffde",
  text60: "#ffffff99",
  text38: "#ffffff61",
  textDisabled: "#494949",
  accentGreen: "#bcdc49",
  accentPurple: "#c45fc6",
  accentLightPurple: "#d893c3",
  accentDarkBlue: "#1b5cfd",
  accentLightBlue: "#9ed3ce",
  accentOrange: "#ffae35",
  tabBarActiveTintColor: "#eee",
  tabBarInactiveTintColor: "#909090",
  dullIcon: "#ffffff",
};

export const lightTheme = {
  primary: "#3498db",
  background: "#f5f5f5",
  foreground: "#121212",
  text: "#333",
};
